"""Generated gRPC stubs, importable as `capture_sdk.proto`.

The stubs are generated by `mise run gen` into `capture_sdk/gen/` (a gitignored
`traffic/v1/...` tree) and use absolute `from traffic.v1 import ...` imports, so that
directory must be on `sys.path`. We add it here — relative to this file, so it resolves
the same in an editable install regardless of where the app's venv lives — and
re-export the message/stub modules so callers write `from capture_sdk.proto import
common_pb2 as cp`.
"""

from __future__ import annotations

import sys
from pathlib import Path

_GEN = Path(__file__).resolve().parent / "gen"
if str(_GEN) not in sys.path:
    sys.path.insert(0, str(_GEN))

from traffic.v1 import common_pb2  # noqa: E402,F401
from traffic.v1 import control_pb2  # noqa: E402,F401
from traffic.v1 import control_pb2_grpc  # noqa: E402,F401
from traffic.v1 import ingest_pb2  # noqa: E402,F401
from traffic.v1 import ingest_pb2_grpc  # noqa: E402,F401
from traffic.v1 import viewer_pb2  # noqa: E402,F401
from traffic.v1 import viewer_pb2_grpc  # noqa: E402,F401
from traffic.v1 import source_pb2  # noqa: E402,F401
from traffic.v1 import source_pb2_grpc  # noqa: E402,F401

__all__ = [
    "common_pb2",
    "control_pb2",
    "control_pb2_grpc",
    "ingest_pb2",
    "ingest_pb2_grpc",
    "viewer_pb2",
    "viewer_pb2_grpc",
    "source_pb2",
    "source_pb2_grpc",
]
